travis:
  secure:
    BINSTAR_TOKEN: RYaySjNNRTu+83wlTSJUCh74qWFmHnEGL07loWDBV+LCbMDT5IvpRF+pPxVZVH1pal6LRU2kaPw+sEr1/ooe+WXw70DYCwanNl37TIKlX5KWrgK2p5KcIPzRs1sIFWPH7iaREAiWuXzKx4JrfU2kJh12ALFW5b2UxRQx+wAbRFu79DWyJpPPKGRLmZJWkRkY2myjSpFOcs951oa32v+uoXEvCb55+Inbf5bzpHhuHkzgqPd/vQnaym3bezoEllsJxbSeLEqbpHmsLckr28KiEA1C32kEtQIPHxaRAkiSS8u7N3eBQS+sdmlQ+c+UnbABTTt68XuuPR9+bliIBOqj/1NrPyuPhBMlMuubF2zp7y7AB+QgTKsjRDgOVCCplnfBzuIazovZSVWR5jAN/ROPfAk8bhcy590D6DnjTy8UzViDkc5G1b7lkT67wNKRI+VFtXliPTF2+WaOm0VyKGhEkYGOwWI1UEiOTgNd35yQ4i8Ql37ZJD1/RvjE2r8IQfIT89FKQqjlXNQ2xX3+xh6jnpoVE3Q0ut2QGvSsrgpDCIGkI7leY7g4QhIqRvadk944h+T0yKsUi5tq/76ESO7M5UZyXeYybtQpmtAmEvmSJG8UcrTikIwMIGjE88/wjMMU/X+SeX6CFzCbl7we+GptgTVIlGbtncxYn5M2CGh/Nh0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
